# default configuration for railyard
{
	"disks": {
		"docker": {
			"mount": "/var/lib/docker",
			"fs": "btrfs",
			"mkfs": [
				"--mixed",
				"--metadata", "single",
				"--data", "single",
				"--label", "docker"
			],
			"options": [
				"compress=zstd:3",
			]
		},
	},
	"shares": {
		"/Users": "/Users",
		"/Volumes": "/Volumes"
	},
	"docker-socket": {
		"host": "run/docker.sock",
		"container": "/run/docker.sock"
	},
	"dockerd": {
		"storage-driver": "btrfs",
	},
}
