# railyard with compressed btrfs and ext4 volumes
{
	"ram": 4096, # in MB, default 25% of total system memory
	"cpu": 2, # number of CPUs, default all available
	"disks": {
		"docker": {
			"mount": "/var/lib/docker",
			"size": "20G",
			"fs": "btrfs",
			"mkfs": [
				"--mixed",
				"--metadata", "single",
				"--data", "single",
				"--label", "docker"
			],
			"options": [
				"defaults",
				"noatime",
				"nodiratime",
				"compress=zstd:12",
			]
		},
		"volumes": {
			"mount": "/var/lib/docker/volumes",
			"size": "40G",
			"fs": "ext4",
			"mkfs": [
				"-m", "0",
				"-T", "ext4",
				"-O", "uninit_bg",
				# allow online resize up to 2TB
				"-E", "lazy_itable_init=1,lazy_journal_init=1,resize=524288000",
				"-F"
			]
		}
	},
	"shares": {
		"/Users": "/Users",
		"/Volumes": "ro:/Volumes"
	},
	"docker-socket": {
		"host": "run/docker.sock",
		"container": "/run/docker.sock"
	},
	"logs": {
		"dir": "logs",
		"max-size": "10M",
		"max-backups": 3,
		"max-age": 7
	},
	"dockerd": {
		"storage-driver": "btrfs",
	},
	"host-iface": "127.0.0.1", # or the name of the host interface to publish on e.g. en0
}
